services:
  umineko-web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./game:/usr/share/nginx/html/game:ro
      - asset-cache:/usr/share/nginx/html/cache

volumes:
  asset-cache:
